---
- name: Download the package
  get_url:
   url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
   dest: ~/amazon-cloudwatch-agent.deb
   mode: '0755'

- name: install cloudwatch agent
  apt:
   deb: ~/amazon-cloudwatch-agent.deb

- name: Cloudwatch agent create config
  shell:
   cmd: amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s
  notify:
     - "Cloudwatch agent is configured"
