services:
  db:
    container_name: db
    image: postgres:latest
    # networks:
    #   - db-app
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      APP_DB_USER: app_db
      APP_DB_PASS: app_db
      APP_DB_NAME: app_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 45s
      interval: 60s
      retries: 10
    restart: always
  backend:
    container_name: backend
    build: .
    # networks:
    #   - db-app
    environment:
      API_KEY: ${API_KEY}
      NAME: ${NAME}
      FLASK_APP: "hello.py"
      DBPASSWORD: postgres
      DBUSER: postgres
      DB: postgres
      DBHOST: db
    depends_on:
      - db

# networks:
#   db-app:
#     driver: bridge
