---
- name: awscli install and upload a file to s3 bucket
  hosts: aws_first_server
  become: yes
  remote_user: ubuntu
  become_user: root

  tasks:
    - name: Install dependencies for awscli
      apt:
        name: "python3-pip"
        state: latest
        update_cache: yes

    - name: Install awscli with pip3
      pip:
        name: "awscli"
        executable: pip3

    - name: Touch a file awscli_installed
      file:
        path: ~/awscli_installed
        state: touch
        mode: u=rw,g=r,o=r

    - name: Copy file awscli_installed to s3 bucket
      shell: aws s3 cp ~/awscli_installed s3://lectures-vkv/

- name: Create and run script on the second aws server
  hosts: aws_second_server
  become: yes
  remote_user: ubuntu
  become_user: root

  tasks:
     - name: Touch the script
       shell: echo touch second_play_execution > /home/ubuntu/secondplay.sh

     - name: Execute the script
       shell: sh /home/ubuntu/secondplay.sh


- name: Download and install cloudwatch agent on the both servers
  hosts: aws_servers
  become: yes
  remote_user: ubuntu
  become_user: root

  tasks:
   - name: Download the package
     get_url:
      url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
      dest: ~/amazon-cloudwatch-agent.deb
      mode: '0755'

   - name: install cloudwatch agent
     apt:
      deb: ~/amazon-cloudwatch-agent.deb

   - name: Cloudwatch agent create config
     shell:
      cmd: amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s
     notify:
        - "Cloudwatch agent is configured"

  handlers:
    - name: Cloudwatch agent is configured
      service:
        name: amazon-cloudwatch-agent
        state: started
