---
- name: Update, download and install cloudwatch agent on the both servers
  hosts: aws_servers
  become: yes
  remote_user: ubuntu
  become_user: root

  roles:
    - update_packages
    - install_cloudwatch
    - touch_a_file

- name: Works with aws first server
  hosts: aws_first_server
  become: yes
  remote_user: ubuntu
  become_user: root
  vars:
    s3_bucket: "lectures-vkv"

  roles:
    - install_packages

  tasks:
    - name: Touch a file awscli_installed
      file:
        path: /home/ubuntu/awscli_installed
        state: touch
        mode: '0644'

    - debug:
        msg: "s3://{{s3_bucket}}/"

    - name: Copy file awscli_installed to s3 bucket
      aws_s3:
        bucket: "{{ s3_bucket }}"
        object: /awscli_installed
        src: /home/ubuntu/awscli_installed
        mode: put


- name: Works with the second aws server
  hosts: aws_second_server
  become: yes
  remote_user: ubuntu
  become_user: root
  vars:
    script_name: "secondplay.sh"

  roles:
    - template_script

  tasks:
     - name: Execute the script
       shell: sh /home/ubuntu/{{script_name}}
